name: daily-updates
on:
  schedule: [{ cron: "0 12 * * *" }]  # 12:00 UTC = 06:00 Costa Rica
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0              # asegura historial suficiente para push
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Debug: ver archivos antes
      - name: Pre-list files
        run: ls -la

      - name: Install deps
        run: python -m pip install --upgrade pip feedparser

      - name: Run collector
        run: python update_sweep.py

      # Debug: confirmar que se crearon los archivos
      - name: Post-list files
        run: |
          ls -la
          echo "----- updates.json (head) -----"
          head -n 20 updates.json || true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git diff --staged --name-only || true
          git commit -m "chore: daily updates" || echo "No changes to commit"
          git push || echo "No push"
